name: "ğŸ‰åŠ å…¥ RMYC-Lab"
description: "æ¬¢è¿æ‚¨åŠ å…¥æˆ‘ä»¬!"
title: "[åŠ å…¥ç”³è¯·]"
labels: ["invitation"]
assignees:
  - Cranyozen
body:
  - type: markdown
    attributes:
      value: |
        æ„Ÿè°¢ä½ å¡«å†™åŠ å…¥è¯¥ç»„ç»‡çš„è¡¨å•
        **æ‰€æœ‰å†…å®¹å‡å¯ä»¥ç”¨ä¸­æ–‡å›ç­”**
  - type: input
    id: contact
    attributes:
      label: è”ç³»æ–¹å¼
      description: ä½ çš„è”ç³»æ–¹å¼ï¼Œå°†åœ¨æŠ€æœ¯å®¡æŸ¥ç¯èŠ‚ä½¿ç”¨ï¼ŒQQ å·ç æœ€ä½³
      placeholder: ä¾‹å¦‚. QQ 11451419
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: ä½ å¯¹ RMYC æ¯”èµ›æœ‰ä»€ä¹ˆæƒ³æ³•
      value: "..."
    validations:
      required: false
  - type: textarea
    id: hobby
    attributes:
      label: ä½ åœ¨ RMYC æ¯”èµ›ä¸­å…´è¶£/è´Ÿè´£çš„æ–¹å‘
      value: "..."
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: å¯¹äºä½ æŠ€æœ¯çš„è¡¥å……æ€§èµ„æ–™
      value: "..."
    validations:
      required: false
